name: CI/CD Pipeline - Billetterie Kubernetes

on:
  push:
    branches:
      - main  # Le pipeline se lance quand tu push sur main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4 # <-- CORRIGÉ : v4 pour enlever le warning Node.js

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3 # <-- CORRIGÉ : v3 pour enlever le warning
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build et Push Backend
        run: |
          docker build -t habibdiao405/projet-back:latest ./back # <-- CORRIGÉ : dossier 'back' (pas 'backend')
          docker push habibdiao405/projet-back:latest

      - name: Build et Push Frontend
        run: |
          docker build -t habibdiao405/projet-frontend:latest ./Frontend # <-- CORRIGÉ : dossier 'Frontend' avec un grand 'F'
          docker push habibdiao405/projet-frontend:latest

  deploy-to-aws:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4 # <-- CORRIGÉ : v4

      - name: Déploiement sur AWS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # On se déplace dans le dossier du projet sur le serveur
            cd /home/ubuntu/DEVOSP_PROJET_GESTION_EVENEMENTIELLE_BILLETERIE
            
            # On récupère les derniers fichiers YAML (k8s/)
            git pull origin main
            
            # On applique la configuration Kubernetes
            kubectl apply -f k8s/
            
            # On force le redémarrage pour charger les nouvelles images dans le bon namespace
            kubectl rollout restart deployment back -n billetterie # <-- CORRIGÉ : ajout du namespace
            kubectl rollout restart deployment front -n billetterie # <-- CORRIGÉ : ajout du namespace et retrait des "??"
